MTCOMMONDIR  := $(MOBILE_TVDIR)/common
MTGUIDIR     := $(MOBILE_TVDIR)/gui_lib/inc
MTEXTDIR     := $(MOBILE_TVDIR)/gui_lib/extinc
MTEXPLOREDIR := $(MOBILE_TVDIR)/explore
INCLUDESDIR += -I$(TOP)/inc

CFLAGS += $(INCLUDESDIR) -I$(MTCOMMONDIR) -I$(MTEXPLOREDIR) -I$(MTGUIDIR) -I$(MTEXTDIR)
CFLAGS += -DRELEASE=$(RELEASE)

ifeq ($(SOC_GENERATION),4755)
	CFLAGS += -DSTATUSPAGE=1
else
	ifeq ($(SOC_GENERATION),4725)
		CFLAGS += -DSTATUSPAGE=1
	else
		CFLAGS += -DSTATUSPAGE=0
	endif
endif

