CC = gcc
AR = ar
 
all : update_file.exe
	cp update_file.exe ../../release

##############################################
update_file.exe:  update_file.o 
	$(CC) -o update_file.exe update_file.o  
###############################################
